= Object Store v2 FAQ
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Where is OSv2 available?

OSv2 is available in every region where Runtime Manager applications can be deployed including:

APAC: Tokyo (ap-northeast-1), Singapore (ap-southeast-1), and Sydney (ap-southeast-2). +
EU: Frankfurt (eu-central-1) and Ireland (eu-west-1). +
North America: Central Canada (ca-central-1), Northern Virginia (us-east-1), and Oregon (us-west-2). +
South America: Sao Paulo (sa-east-1). +
Also London (eu-west-2) can be accessed from the US cloud, but not the EU cloud.

== What Mule versions support OSv2?

Mule 3.8.5 and above, and all 4.x versions.

== Is OSv2 persistent in the same region as the worker?

Yes, OSv2 is in the same region as the worker where the application is initially deployed. For example, if you deploy to the Singapore region, the object store persists in the Singapore region.

IMPORTANT: If after the first deploy, you move the app to a different region, OSv2 remains in the original region to avoid data loss. Your use of OSv2 never moves from one region to another. When you need to deploy both an app and object store to a different region, delete the application and re-upload the app into the new region. This action *loses all the data* that may exist in the storage.

== How long can data persist in OSv2?

Object Store v2 data persists 30 days. The expiry time is reset if an update to that key occurs. If there is no update, the key is deleted at the 30 day mark.

== What's the maximum number of keys that can persist in OSv2?

In OSv2 there is no limit on the number of keys per application. In Object Store v1, the limit was 100,000 keys and attempts to store more were rejected.

== Where is the OSv2 REST API portal?

This API is available in the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Platform Developer's portal].

== Where is the Object Store connector?

https://www.anypoint.mulesoft.com/exchange/?search=objectstore[Anypoint Exchange] provides assets for the Mule 3 Object Store connector used by Anypoint Studio 6 and the Mule 4 Object Store connector used by Studio 7.

== Do I need a different Object Store connector for Object Store v2 and Object Store v1?

All versions of Mule's Object Store Connector work with both OSv1 and OSv2.

== Are there rate limits on OSv2?

Customers who have not purchased a separate Object Store SKU are rate limited to 10 transactions per second per application.  If an application for an account that has not purchased the OSv2 SKU exceeds the rate limit, further requests are not processed for a time and a 429 HTTP error status code results. To go beyond the base 10 TPS rate limit, contact your MuleSoft account team.

== Can OSv2 be shared between workers?

An Object Store and its contents (keys, values) is accessible to all CloudHub workers of the one Mule application that defines and therefore owns that Object Store. However, other Mule applications and the CloudHub workers on which they execute cannot access this Object Store and its contents. If needed, you can use the REST API to read from one application and store to another.

////
== Does Object Store replicate cached data across CloudHub workers?

Data stored in Object Store V1 or V2 is in a separate service that is accessible
to any CloudHub worker in a single application, and is shared across workers. Data
only goes to Object Store V2, if you set `objectStore-ref="_defaultUserObjectStore"`
in your Mule XML flow. If not set, Object Store references stay in-memory in a
single worker.

Mule 3 example XML flow:

[source,xml,linenums]
----
<objectstore:config name="ObjectStore__Connector" partition="mypartition"
 objectStore-ref="_defaultUserObjectStore" doc:name="ObjectStore: Connector"/>
----

////

== Can OSv2 be used on premises?

No, but applications running on-premises can use the OSv2 REST API to store data in OSv2 and retrieve it.

== How is OSv2 data secured?

Object Store v2 uses TLS for secure transport. Data at rest is stored using FIPS 140-2 compliant encryption standards.  If you require a higher level of security, we recommend that you encrypt sensitive data before writing it to the Object Store.

== Does Object Store cache data or do I/O for each read and write?

Object Store V2 does I/O for each read and write. With Object Store V2, the API call is localized to the
same data center as the Runtime Manager application.

== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Exchange Object Store v2]
* https://www.anypoint.mulesoft.com/exchange/org.mule.modules/mule-module-objectstore/[Mule 3 Object Store Connector]
* https://www.anypoint.mulesoft.com/exchange/org.mule.connectors/mule-objectstore-connector/[Mule 4 Object Store Connector]
* xref:index.adoc[Object Store Documentation]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com/s/knowledge[Knowledge Base Articles]
