= Object Store v2 REST APIs 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: osv2, os2, object store, store, rest, apis

The Object Store v2 APIs enable you to use REST to temporarily store and retrieve key-value pairs in a single
application, and to retrieve Object Store usage statistics for your organization.

Object Store provides these APIs:

* <<Object Store API>>
* <<Object Store Stats API>>

In the Stats API portal, click *Download* to download the API as RAML, OAS, or as a Mule 3 or Mule 4 connector file.


== Authorize API Access

* <<Object Store API>>
+
Get a token by supplying the client ID and client secret for an app.
* <<Object Store Stats API>>
+
Get an access token for an Anypoint Platform user.

== Object Store API  

The Object Store API reads and writes `key,list` values, which is different from 
the Object Store connector, which reads and writes in the `key,value` format.

[NOTE]
If an application writes to an object store using the REST interface and reads with the
Mule 3 object store connector from the same key, the read can only retrieve the value at element 0 of
the list. 
Therefore, when using the REST API, only use the API for writing and reading content
from the Object Store.
Alternatively, you can use the API to only write to index 0. This limitation does
not apply to the Mule 4 and Anypoint Studio object store connector.

The following table compares the Object Store REST API operations to Object Store connector operations:

[%header,cols="20a,50a,30a"]
|===
|Object Store v2 API |Object Store v2 REST API Operations |ObjectStore Connector Operation

|POST |

* Object Store:
** TTL in seconds for the object store - by default the TTL is 2,592,000 seconds (30 days). 
** Persistence property.
** Usage limits for each application or environment, includes options for limiting based on keys or size and how to enforce them.
* Key and list (item) value.

|Store
|GET |

* Get keys
* Get item
* Get items
* Get all items
* Get regions for an organization

|Contains + Retrieve + Retrieve all keys + Retrieve and store (Retrieve part)
|PUT |

* Put item as String
* Put item as Number
* Put item as confirmable String
* Put store

|Dual store *&#8224;* + Store
|DELETE |

* Remove object store
* Delete key
* Delete item

|Remove
|===

*&#8224;* The Dual Store operation in the Object Store connector consists of two operations where the key and value are stored and then the values reversed. The Dual Store operation acts the same as two Object Store v2 "Put item as String" calls to accomplish these results:

. `objectStore.store(key, value);`
. `objectStore.store(value, key);`

The maximum number of keys you can obtain in each GET operation is 25.


=== Prerequisites 

Deploy an application to CloudHub. 

Accessing the Object Store v2 API works as follows:

* Access the REST API
* View the App Client ID and Secret

=== Access the REST API

Set up an application like Postman to access the object store.
Obtain the `access_token` value:

. Configure the object store access URL to:
+
`_osBaseUrl_/api/v1/organizations/:ORGANIZATION_ID/environments/:environmentId/stores/myTestStoreId/objects`
+
For values to use for `_osBaseUrl_`, see the following table.
. Configure the application with HTTP headers and body for values to store to or read from
the object store.
. Send the operation to the object store API.


You can use the following domains for the value of `_osBaseUrl_` in the access URL:

[%header,cols="10a,80a"]
|===
|Control Plane|Domain
.9+|prod | object-store-us-east-2.anypoint.mulesoft.com
| object-store-us-west-1.anypoint.mulesoft.com
| object-store-us-west-2.anypoint.mulesoft.com
| object-store-ap-southeast-1.anypoint.mulesoft.com
| object-store-ap-southeast-2.anypoint.mulesoft.com
| object-store-ap-northeast-1.anypoint.mulesoft.com
| object-store-ca-central-1.anypoint.mulesoft.com
| object-store-eu-west-2.eu1.anypoint.mulesoft.com
| object-store-sa-east-1.anypoint.mulesoft.com
.2+|prod-eu | object-store-eu-central-1.eu1.anypoint.mulesoft.com
| object-store-eu-west-1.eu1.anypoint.mulesoft.com
|===



=== View the App Client ID and Secret

To authenticate an application for use with the Object Store API, 
you need the client ID and client secret for the application.

If you are the organization administrator for your Anypoint Platform account,
you can view the client ID and client secret for the app from the *Object Store* menu:

. Log into *Anypoint Platform > Runtime Manager*.
. Click an application that has Object Store access and click *Manage Application*.
+
The app can be running or undeployed.
. If the app is not yet associated with Object Store v2, click the checkbox and apply changes.
. Click the *Object Store* menu in the left navigation area, then click *Show Client Credentials*.
. Click *Copy to Clipboard* and paste the client ID or secret value into the curl application 
that you use to authenticate the REST API.

=== View the Bearer Token

After you have the client ID and secret for your application, you can get the bearer ID using a curl command:

[source,console,linenums]
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/oauth2/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=CLIENT_ID_VALUE&client_secret=CLIENT_SECRET_VALUE&grant_type=client_credentials'
----

Substitute CLIENT_ID_VALUE and CLIENT_SECRET_VALUE for the client ID and secret.

The output appears as:

[source,json,linenums]
----
{
    "access_token": "42424242-5454-4242-5454-425442544254",
    "token_type": "bearer"
}
----


=== Example: Retrieve a List of Object Stores

The following procedures assume you have already created an application and given it access to Object Store v2.

[NOTE]
Get the Client ID and Secret as described in <<View the App Client ID and Secret>>.

==== Get Environment and Organization IDs

In *Access Management > Environments*, click the environment where the application resides. Copy
the environment ID from the URL, for example:

`+https://anypoint.mulesoft.com/accounts/#/cs/core/environments/edit/badd09f00f004242badd0942+`

In *Access Management > Organization*, copy your *Organization ID*.

==== View List of Object Stores

Submit this command replacing `BEARER_ID` with your bearer ID, `ORG_ID` with your organization ID, and `ENV_ID` with your environment ID.

[source,console,linenums]
----
curl -X GET \
> -H 'authorization: bearer BEARER_ID' \
> 'https://object-store-us-east-1.anypoint.mulesoft.com/api/v1/organizations/ORG_ID/environments/ENV_ID/stores'
----

The output has values similar to:

[source,json,linenums]
----
{"values":[{"storeId":"APP_demo-aug12_DEFAULT_USER_STORE","encrypted":true,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600},
{"storeId":"APP_objectstore42_DEFAULT_USER_STORE","encrypted":false,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600},
{"storeId":"APP_objectstore42_mypartition","encrypted":false,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600}],"nextPageToken":null}
----

== Object Store Stats API 


The Object Store Stats API enables you to retrieve statistics on your Object Store usage.

Use the Stats API to view your entire organization’s usage of Object Store for billing purposes:

* Usage per environment
* Usage per organization

For more information, see the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2-stats/minor/1.0/pages/home/[Object Store v2 Stats API] on the MuleSoft Developer Portal.

=== Authorize API Access

To access the Stats API, you must first authenticate using the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/[Anypoint Access Management API].

To use the Stats API, you can get the access token from the Anypoint Platform user.
The access token is also known as the Bearer.
The default time to live (TTL) for the access token is 60 minutes.


You can get the organization ID and environment ID in the `payload.txt` file that Anypoint Platform creates for any auditable action in Object Store. 
// See xref:access-management::audit-logging.adoc#to-query-audit-logging-for-anypoint-mq[MQ Audit Logging]. 

You can use this `curl` command to get the access token:

[source,bash]
----
curl -X POST -H "Content-Type: application/json" -d '{"username":"USERNAME", "password":"PASSWORD"}' https://anypoint.mulesoft.com/accounts/login
----

This returns output similar to:

[source,json,linenums]
----
{
  "access_token": "42424242-4242-4242-4242-424242424242",
  "token_type": "bearer",
  "redirectUrl": "/home/"
}
----

=== Retrieve Usage Metrics by Environment 

The Stats API can be used to sum up the usage for Object Store across all environments for a particular organization. This is not real-time and has a latency.

`/environments/ENVIRONMENT_ID?startDate=...&endDate=...&period=...`

*Sample Request and Response:*

[source,example,linenums]
----
https://anypoint.mulesoft.com/object-store-stats/stats/api/v1/organizations/ORGANIZATION_ID/environments/ENVIRONMENT_ID
?startDate=Thursday, 8 Nov 2018 04:49:37 GMT
&endDate=Sun, 11 Nov 2018 04:60:44 GMT
&period=1day

[
    {
        "timestamp": "2018-11-08T00:00Z",
        "apiRequestCount": 0,
        "messageReceiptCount": 0,
        "billableUnitCount": 0,
        "messageByteCount": 0
    }
]
----

=== Retrieve Usage Metrics by Organization

The Stats API can be used to sum up the usage for Object Store across the master business organization:

`/organizations/ORGANIZATION_ID?startDate=...&endDate=...&period=...`

*Sample Request and Response:*

[source,example,linenums]
----
https://anypoint.mulesoft.com/mq/stats/api/v1/organizations/ORGANIZATION_ID?
startDate=Thursday, 8 Nov 2018 04:49:37 GMT
&endDate=Sun, 11 Nov 2018 04:60:44 GMT
&period=1day

[
    {
        "timestamp": "2018-11-08T00:00Z",
        "apiRequestCount": 0,
        "messageReceiptCount": 0,
        "billableUnitCount": 0,
        "messageByteCount": 0
    }
]
----

[[exstatapi]]
=== Example: Object Store Stats API

NOTE: To access the Object Store Stats API, you must first authenticate using the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/[Anypoint Access Management API].


Example request to list statistics for July 26 to July 28, 2018:

[source,json,linenums]
----
curl -X GET \
'https://anypoint.mulesoft.com/mq/stats/api/v1/organizations/ORGANIZATION_ID/environments/ENVIRONMENT_ID/regions/REGION_URL/queues/randomQueue/?startDate=Thu%2C%2026%20Jul%202018%2000%3A00%3A00%20GMT&endDate=Sat%2C%2028%20Jul%202018%2020%3A00%3A00%20GMT&period=600' \
  -H 'authorization: Bearer BEARER_TOKEN' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: ACCESS_TOKEN'
----

Example response:

[source,json,linenums]
----
{
  "destination": "myDestination",
  "messages": [
    {
      "date": "2018-07-26T00:00:00.000+0000",
      "value": 2126
    },
    {
      "date": "2018-07-27T00:00:00.000+0000",
      "value": 2126
    },
    {
      "date": "2018-07-28T00:00:00.000+0000",
      "value": 587
    }
  ],
  "inflightMessages": [
    {
      "date": "2018-07-26T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-27T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-28T00:00:00.000+0000",
      "value": 0
    }
  ],
  "messagesVisible": [
    {
      "date": "2018-07-26T00:00:00.000+0000",
      "value": 2126
    },
    {
      "date": "2018-07-27T00:00:00.000+0000",
      "value": 2126
    },
    {
      "date": "2018-07-28T00:00:00.000+0000",
      "value": 587
    }
  ],
  "messagesSent": [
    {
      "date": "2018-07-26T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-27T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-28T00:00:00.000+0000",
      "value": 0
    }
  ],
  "messagesReceived": [
    {
      "date": "2018-07-26T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-27T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-28T00:00:00.000+0000",
      "value": 0
    }
  ],
  "messagesAcked": [
    {
      "date": "2018-07-26T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-27T00:00:00.000+0000",
      "value": 0
    },
    {
      "date": "2018-07-28T00:00:00.000+0000",
      "value": 0
    }
  ]
}
----


== See Also

* https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/public/apis/16510/versions/17620/files/root[Object Store v2 api.raml]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Object Store v2 API in Anypoint Exchange]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2-stats/[Object Store v2 Stats API in Anypoint Exchange]
* xref:connectors::object-store/object-store-connector.adoc[Object Store Connector - Mule 4]
* xref:3.9@mule-runtime::object-store-connector.adoc[Object Store Connector - Mule 3]
* xref:osv2-faq.adoc#how-long-can-data-persist-in-object-store-v2[How long can data persist in Object Store v2?]
* xref:runtime-manager::deploying-to-cloudhub.adoc[Deploy to CloudHub]
