= FAQ: Object Store v2
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Where is Object Store v2 available?

Object Store v2 is available in every xref:runtime-manager::cloudhub-networking-guide.adoc#regional-services[region] where Runtime Manager (CloudHub) apps can be deployed.

== What Mule versions support Object Store v2?

* Mule runtime engine 3.8.5 and later
* All Mule runtime engine 4.x versions
+
Mule 4 supports Object Store v2, but does not support Object Store v1.


== Can I use Object Store v2 for apps deployed to on-premises servers?

// Shared onPrem 
include::partial$osv2-faq.adoc[tag=faqOnPrem]


For on-premises deployments, you can use the object store included in Mule.
For information about the Mule object store, see xref:mule-runtime::mule-object-stores.adoc[Store Application Data Using Object Stores].



== How can I see usage data?

To view API request data, see xref:osv2-usage.adoc[View Usage Graphs].
 
== What happens when the transaction limit for my subscription is reached?

An Object Store v2 subscription pack allows up to 100 million transactions per month for an Anypoint Platform organization. This limit is applied across all Production and non-Production environments.
You can use the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2-stats/[Object Store v2 Stats API] to monitor usage.


//Shared Usage Overage 
include::partial$osv2-faq.adoc[tag=faqUsageOverage]


== Is Object Store v2 persistent in the same region as the worker?

Yes, Object Store v2 is in the same region as the worker where the app is initially deployed. For example, if you deploy to the Singapore region, the object store persists in the Singapore region.

IMPORTANT: If after the first deploy, you move the app to a different region, Object Store v2 remains in the original region to avoid data loss. Your use of Object Store v2 never moves from one region to another. When you need to deploy both an app and object store to a different region, delete the app and re-upload the app into the new region. This action loses all the data that may exist in the storage.

== Can an app deployed to CloudHub access the object store of another CloudHub app?

You can configure a Mule app to use the Object Store REST API to store and retrieve 
values from an object store in another Mule app. 

However, Object Store v2 is not designed for app-to-app communication.
To share data between two Mule 4 apps, use a queue in xref:mq::index.adoc[Anypoint MQ].

For information about object store limitations, see xref:connectors::object-store/object-store-connector.adoc#object-store-limitations[Object Store Limitations].

For information about the Object Store REST API, see 
https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Object Store v2 API] on Exchange. 



== What are the limits on an object store?

The total size of an object store is not limited, but each value is limited to 10 MB.

Every API call (via the connector or API) to Object Store v2 counts toward the API rate limiting (transactions per second (TPS)):

* Base subscription: 10 TPS per app
* Premium add-on subscription: 100 TPS per app

== What is the maximum number of keys that can persist in Object Store v2?

In Object Store v2, there is no limit on the number of keys per app.

== How many characters can a key have?

// Shared keySize 
include::partial$osv2-faq.adoc[tag=faqKeySize]

// Shared keyChars 
include::partial$osv2-faq.adoc[tag=faqKeyChars]

== What are the advantages of using partitions?

You can use partitions to divide the object store into separate areas for your stored and retrieved keys.
Partitions are logical, rather than physical, structures.
For this reason, data access time is the same, whether you store keys in one partition or multiple partitions.


== How long can data persist in Object Store v2?

The maximum TTL (time to live) is 2592000 seconds (30 days).

The `entryTtl` value, specified in the global configuration parameters for the connector,
determines when to evict key-value pairs from the store.

The TTL can be either _rolling_ or _static_:

Rolling::
Accessing the data extends the TTL for 30 days.
+
The minimum rolling TTL is 1 second.
The maximum rolling TTL is unlimited as long as the data continues to be accessed.
Static::
The value of `entryTtl` determines when the data is evicted.
+
The minimum static TTL is 1 second.
The maximum (and default) static TTL is 2592000 seconds (30 days).
If the `entryTtl` value is greater than 30 days, TTL is set to the maximum value of 2592000 seconds (30 days) without returning an error.
+
//Shared Static TTL 
include::partial$osv2-faq.adoc[tag=faqStaticTTL]

If the app doesn't specify a value for `entryTtl`, the default value depends on the Mule version.

* Mule versions 4.2.1 and later:
+
Object stores have a rolling TTL by default.
+
If the data is accessed at least once a week, the TTL is extended for 30 days.
Otherwise, it is evicted in the next 7 to 30 days from the most recent expiration date.
[NOTE]
Rolling TTL is available for all apps using Mule version 4.2.1 and later.
* Mule versions earlier than 4.2.1:
+
Object stores have a static TTL of 30 days by default.
+
//Shared Static TTL 
include::partial$osv2-faq.adoc[tag=faqStaticTTL]

For information about configuring TTL, see 
xref:osv2-guide.adoc#configure-a-custom-time-to-live-period[Configure a Custom Time to Live Period].

== Where is the Object Store v2 REST API portal?

The Object Store v2 APIs are available in the Anypoint Platform Developer's portal:

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Exchange Object Store v2]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2-stats/[Anypoint Exchange Object Store v2 Stats]


== Where is the Object Store connector?

https://www.anypoint.mulesoft.com/exchange/?search=objectstore[Anypoint Exchange] provides assets for the Mule 3 Object Store connector used by Anypoint Studio 6, and for the Mule 4 Object Store connector used by Studio 7.

== Do I need a different Object Store connector for Object Store v2 and Object Store v1?

All versions of Mule's Object Store Connector work with both Object Store v1 and Object Store v2.

== Why are Object Store values in binary format?

When you view an Object Store key in Runtime Manager, the value for the key displays as `[binary value] BINARY`.
Mule 4 wraps values into a Mule object that causes them to be only visible in binary through Anypoint Platform. Behind the scenes, Mule 4 executes binary serialization with the Mule internal serializer. The user interface cannot deserialize the object, hence it can only tell you that the value is now binary in the user interface.

To view the key value, you need an Object Store retrieve flow in your app's connector, such as:

[source,xml,linenums]
----
<flow name="Retrieve" >
	<http:listener doc:name="Listener" config-ref="HTTP_Listener_config1"
		path="/retrieve">
		<ee:repeatable-file-store-stream />
	</http:listener>
	<os:retrieve doc:name="Retrieve"
		key="#[attributes.queryParams.key]"
		objectStore="Object_store1"/>
</flow>
----

For more information, see xref:osv2-tutorial.adoc#create-a-studio-7-project[Tutorial: Create a Studio 7 Project].

== Are there rate limits on Object Store v2?

Customers who have not purchased a separate Object Store SKU are rate limited to 10 transactions per second per app.  If an app for an account that has not purchased the Object Store v2 SKU exceeds the rate limit, further requests are not processed for a time and a 429 HTTP error status code results. To go beyond the base 10 TPS rate limit, contact your MuleSoft account team.

== How is Object Store v2 data secured?

Object Store v2 uses TLS for secure transport. Data at rest is stored using FIPS 140-2 compliant encryption standards.  If you require a higher level of security, we recommend that you encrypt sensitive data before writing it to the Object Store.

== Does Object Store cache data or perform I/O for each read and write?

Object Store v2 performs I/O for each read and write. With Object Store v2, the API call is localized to the
same data center as the Runtime Manager app.

== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Exchange Object Store v2 API]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2-stats/[Anypoint Exchange Object Store v2 Stats API]
* xref:osv2-guide.adoc#configure-a-custom-time-to-live-period[Configure a Custom Time-to-Live Period]
* xref:osv2-guide.adoc#create-object-store-partitions[Create Object Store Partitions]
* xref:connectors::object-store/object-store-connector.adoc[Object Store Connector - Mule 4]
* xref:3.9@mule-runtime::object-store-connector.adoc[Object Store Connector - Mule 3]
* https://help.mulesoft.com/s/article/The-Different-Types-of-Object-Stores-Explained[The Different Types of Object Stores Explained]
