= REST API: Object Store v2
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: osv2, os2, object store, store, rest, apis

Anypoint Object Store v2 (Object Store v2) provides a REST API that enables you to get and store key-value pairs.

An object store works with a single application to temporarily store application data.
To authenticate access, you need the client ID and client secret for the application, which Object Store
displays in the Runtime Manager in Anypoint Platform.
See <<View the App Client ID and Secret>>.

The maximum number of keys you can obtain in each GET operation is 25.


== Object Store v2 Operations

The Object Store connector reads and writes in the `key,value` format; whereas Object Store v2 API reads and writes `key,list` values.

[NOTE]
If an application writes to an object store using the REST interface and reads with the
Mule 3 object store connector from the same key, the read can only retrieve the value at element 0 of
the list. Therefore, when using the REST API, only use the API for writing and reading content
from the Object Store. Alternatively, you can use the API to only write to index 0. This limitation does
not apply to the Mule 4 and Anypoint Studio object store connector.

The following table compares the Object Store REST API operations to Object Store connector operations:

[%header,cols="20a,50a,30a"]
|===
|Object Store v2 API |Object Store v2 REST API Operations |ObjectStore Connector Operation

|POST |

* Object Store:
** TTL, in seconds, for the object store.
+
The default and maximum TTL is 2,592,000 seconds (30 days). See xref:osv2-faq.adoc#how-long-can-data-persist-in-object-store-v2[How long can data persist in Object Store v2?]
** Persistence property.
** Usage limits for each application or environment, includes options for limiting based on keys or size and how to enforce them.
* Key and list (item) value.

|Store
|GET |

* Get keys
* Get item
* Get items
* Get all items
* Get regions for an organization

|Contains + Retrieve + Retrieve all keys + Retrieve and store (Retrieve part)
|PUT |

* Put item as String
* Put item as Number
* Put item as confirmable String
* Put store

|Dual store *&#8224;* + Store
|DELETE |

* Remove object store
* Delete key
* Delete item

|Remove
|===

*&#8224;* The Dual Store operation in the Object Store connector consists of two operations where the key and value are stored and then the values reversed. The Dual Store operation acts the same as two Object Store v2 "Put item as String" calls to accomplish these results:

. `objectStore.store(key, value);`
. `objectStore.store(value, key);`



== Object Store v2 APIs Workflow

Before deploying an object store application, log into Anypoint Platform and use Anypoint Runtime Manager (Runtime Manager) to reduce the number of allowed workers so that you can add a new application.

Accessing the Object Store v2 API works as follows:

* Deploy an Application
* Access the REST API
* View the App Client ID and Secret

== Deploy an Application

. Log into Anypoint Platform.
. Click *Runtime Manager*.
. If you have an existing application, click it and click *Manage Application*.
+
If this is your first use, create an application in Anypoint Studio. When done developing, right-click the project name in Package Explorer and
click *Anypoint Platform > Deploy to Cloud*.
+
. In the Runtime Manager *Deploying Application* menu:
+
.. If the application name has a red X, change the name so that the green check mark appears after the name.
+
The application name you choose becomes the name users access your application with.
For example, if you name your application `mydemo`, users can access your application at
`+http://mydemo.cloudhub.io/+`.
+
.. Ignore the *Deployment Target* and *Application File* fields. Anypoint Studio
fills in this information for you.
.. If needed, change the Mule Runtime engine version field from the drop-down list.
.. If needed, change the worker size field.
.. Click *Deploy Application*.

== Access the REST API

Set up an application like Postman to access the object store.
Obtain the `access_token` value:

. Configure the object store access URL to:
+
`_osBaseUrl_/api/v1/organizations/:ORGANIZATION_ID/environments/:environmentId/stores/myTestStoreId/objects`
+
For values to use for `_osBaseUrl_`, see the following table.
. Configure the application with HTTP headers and body for values to store to or read from
the object store.
. Send the operation to the object store API.


You can use the following domains for the value of `_osBaseUrl_` in the access URL:

[%header,cols="10a,80a"]
|===
|Control Plane|Domain
.9+|prod | object-store-us-east-2.anypoint.mulesoft.com
| object-store-us-west-1.anypoint.mulesoft.com
| object-store-us-west-2.anypoint.mulesoft.com
| object-store-ap-southeast-1.anypoint.mulesoft.com
| object-store-ap-southeast-2.anypoint.mulesoft.com
| object-store-ap-northeast-1.anypoint.mulesoft.com
| object-store-ca-central-1.anypoint.mulesoft.com
| object-store-eu-west-2.eu1.anypoint.mulesoft.com
| object-store-sa-east-1.anypoint.mulesoft.com
.2+|prod-eu | object-store-eu-central-1.eu1.anypoint.mulesoft.com
| object-store-eu-west-1.eu1.anypoint.mulesoft.com
|===

== View the App Client ID and Secret

If you are the organization administrator for your Anypoint Platform
account, you can view the client ID and client secret for an app from the *Object Store* menu.

The client ID and secret are required to authenticate an application for use with the Object Store v2 REST API.

. Log into *Anypoint Platform > Runtime Manager*.
. Click an application that has Object Store access and click *Manage Application*. The app can be running or undeployed.
. If the app is not yet associated with Object Store v2, click the checkbox and apply changes.
. Click the *Object Store* menu in the left navigation area, then click *Show Client Credentials*.
. Click the *Copy to Clipboard* icon, and paste the client ID or secret value into your curl application that you use to authenticate the REST API.

== View the Bearer Token

After you have the client ID and secret for your application, you can get the bearer ID using a curl command:

[source,console,linenums]
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/oauth2/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=CLIENT_ID_VALUE&client_secret=CLIENT_SECRET_VALUE&grant_type=client_credentials'
----

Substitute CLIENT_ID_VALUE and CLIENT_SECRET_VALUE for the Client ID and secret.

The output appears as:

[source,json,linenums]
----
{
    "access_token": "42424242-5454-4242-5454-425442544254",
    "token_type": "bearer"
}
----

== Example: Retrieve a List of Object Stores

The following procedures assume you have already created an application and given it access to Object Store v2.

*Note:* Get the Client ID and Secret as described in <<View the App Client ID and Secret>>.

=== Get Environment and Organization IDs

In *Access Management > Environments*, click the environment where the application resides. Copy
the environment ID from the URL, for example:

`+https://anypoint.mulesoft.com/accounts/#/cs/core/environments/edit/badd09f00f004242badd0942+`

In *Access Management > Organization*, copy your *Organization ID*.

=== View List of Object Stores

Submit this command replacing `BEARER_ID` with your bearer ID, `ORG_ID` with your organization ID, and `ENV_ID` with your environment ID.

[source,console,linenums]
----
curl -X GET \
> -H 'authorization: bearer BEARER_ID' \
> 'https://object-store-us-east-1.anypoint.mulesoft.com/api/v1/organizations/ORG_ID/environments/ENV_ID/stores'
----

The output has values similar to:

[source,json,linenums]
----
{"values":[{"storeId":"APP_demo-aug12_DEFAULT_USER_STORE","encrypted":true,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600},
{"storeId":"APP_objectstore42_DEFAULT_USER_STORE","encrypted":false,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600},
{"storeId":"APP_objectstore42_mypartition","encrypted":false,"permanentOsFlag":false,
  "persistent":true,"defaultTtlSeconds":1209600,"defaultConfirmationTtlSeconds":600}],"nextPageToken":null}
----

== See Also

* xref:osv2-faq.adoc#how-long-can-data-persist-in-object-store-v2[How long can data persist in Object Store v2?] 
* https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/public/apis/16510/versions/17620/files/root[Object Store v2 api.raml]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Object Store v2 API in Anypoint Exchange]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2-stats/[Object Store v2 Stats API in Anypoint Exchange]
* xref:connectors::object-store/object-store-connector.adoc[Object Store Connector - Mule 4]
* xref:3.9@mule-runtime::object-store-connector.adoc[Object Store Connector - Mule 3]
