= Retrieving Usage Metrics with Anypoint APIs

Depending on your control plane, you use different APIs to retrieve Object Store v2 usage metrics.

[%header,cols="15,15,30"]
|===
| Control Plane | API | More Information
| https://anypoint.mulesoft.com/[US Cloud] | Object Store v2 Stats Stats | <<retrieve-metrics-stats-api>>
| https://eu1.anypoint.mulesoft.com/[EU Cloud] | Object Store v2 Stats Stats | <<retrieve-metrics-stats-api>>
| https://ca1.platform.mulesoft.com/[Canada Cloud] (Hyperforce)| Metering API | <<retrieve-metrics-metering-api>>
| https://jp1.platform.mulesoft.com/[Japan Cloud] (Hyperforce) | Metering API | <<retrieve-metrics-metering-api>>
|===

[[retrieve-metrics-stats-api]]
== Retrieve Usage Metrics with Object Store v2 Stats API

To retrieve Object Store v2 usage metrics on US Cloud or EU Cloud,
use the Object Store v2 Stats API:

* xref:osv2-apis.adoc#usage-by-org[Get Usage Metrics by Organization]
* xref:osv2-apis.adoc#usage-by-env[Get Usage Metrics by Environment]
* xref:osv2-apis.adoc#usage-by-region[Get Usage Metrics by Region]
* xref:osv2-apis.adoc#usage-by-store[Get Usage Metrics by Store]


[[retrieve-metrics-metering-api]]
== Retrieve Usage Metrics with Anypoint Metering Query API

To retrieve Object Store v2 usage metrics on Canada Cloud or Japan Cloud, use the Metering Query API:

* <<get-eff-api-req-root-org>>
* <<get-eff-api-req-org-id>>
* <<get-eff-api-req-org-env-id>>
* <<get-eff-api-req-org-env-store-id>>



=== Before You Begin

* xref:osv2-apis.adoc#get-bearer-token[Get a bearer token] for an Anypoint Platform user account that has the Usage Viewer permission for your root organization.
* Familiarize yourself with how Object Store v2 uses xref:osv2-usage.adoc[effective API requests].
* Use the information in this table to construct your queries:
+
[%header,cols="15,45a"]
|===
| Parameter | Description
| TIMESERIES | How to group the output:

* Monthly: `P1M`
* Daily: `P1D`
* Hourly: `PT1H`

| BETWEEN  | Time frame to retrieve metrics for (timestamp specified in https://currentmillis.com/[milliseconds]).
| INSTANCE | Anypoint Platform instance:

* Canada Cloud: https://ca1.platform.mulesoft.com/metering/usage
* Japan Cloud: https://jp1.platform.mulesoft.com/metering/usage
|===



[[get-eff-api-req-root-org]]
=== Get Effective API Requests by Root Org

Use a command like this:

[source,bash,linenums]
----
curl --location 'INSTANCE/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT effective_api_requests FROM object_store_effective_api_requests_count WHERE timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T19:55:33.487512271Z"
   },
   "data":[
      {
         "effective_api_requests":200000.0,
         "timestamp":1730419200000
      }
   ]
}
----


[[get-eff-api-req-org-id]]
=== Get Effective API Requests for a Specific Org

Use a command like this:

[source,bash,linenums]
----
curl --location 'INSTANCE/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, effective_api_requests FROM object_store_effective_api_requests_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T19:57:51.677748123Z"
   },
   "data":[
      {
         "effective_api_requests":150000.0,
         "org_id":"66310c16-bce5-43c4-b978-5945ed2f99c5",
         "timestamp":1730419200000
      }
   ]
}
----

[[get-eff-api-req-org-env-id]]
=== Get Effective API Requests for a Specific Org and Environment

Use a command like this:

[source,bash,linenums]
----
curl --location 'INSTANCE/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT org_id, env_id, effective_api_requests FROM object_store_effective_api_requests_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND env_id = '\''40eeb638-348c-4d80-9db6-7baf88b2d28f'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T20:01:21.021744950Z"
   },
   "data":[
      {
         "env_id":"40eeb638-348c-4d80-9db6-7baf88b2d28f",
         "effective_api_requests":100000.0
         "org_id":"66310c16-bce5-43c4-b978-5945ed2f99c5",
         "timestamp":1730419200000
      }
   ]
}
----

[[get-eff-api-req-org-env-store-id]]
=== Get Effective API Requests for a Specific Org, Environment, and Store

Use a command like this:

[source,bash,linenums]
----
curl --location 'INSTANCE/metering/usage/api/v1/meters:search' \
--header 'Authorization: bearer ***' \
--header 'Content-type: application/json' \
--data '{
    "query": "SELECT store_id, org_id, env_id, effective_api_requests FROM object_store_effective_api_requests_count WHERE org_id = '\''66310c16-bce5-43c4-b978-5945ed2f99c5'\'' AND env_id = '\''40eeb638-348c-4d80-9db6-7baf88b2d28f'\'' AND store_id = '\''PostmanTestStore'\'' AND timestamp BETWEEN 1731207600000 AND 1731963949248 TIMESERIES P1M"
}'
----

This command returns output similar to:

[source,json,linenums]
----
{
   "metadata":{
      "responseAsOf":"2024-11-19T20:03:57.680851659Z"
   },
   "data":[
      {
         "store_id":"PostmanTestStore",
         "env_id":"40eeb638-348c-4d80-9db6-7baf88b2d28f",
         "effective_api_requests":500.0,
         "org_id":"66310c16-bce5-43c4-b978-5945ed2f99c5",
         "timestamp":1730419200000
      }
   ]
}
----

== See Also

* xref:osv2-usage.adoc[]
* xref:osv2.apis.adoc#osv2-stats-api[Object Store v2 Stats API]
* Placeholder link to the OSv2 Regions topic
* Placeholder link to the OSv2 on HF topic
* Placeholder for Anypoint Metering API
